name: publish

on:
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        description: "burrito (Minor Release)"
        default: "burrito-next"
        options:
        - burrito-next (Preview build)
        - burrito (Minor Release)
        required: true

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - name: Get Version Tags
        run: |

          git init
          git remote add origin https://github.com/${{ github.repository }}.git
          tags=$(git ls-remote --tags origin | awk -F/ '{print $3}' | grep -v '\^{}')

          echo "$tags"

          highest_version=$(echo "$tags" | grep -E "burrito-[0-9]+\.[0-9]+\.[0-9]+" | sort --version-sort --reverse | head -n 1)
          
          version=${highest_version#burrito-}
          
          IFS='.' read -r major minor patch <<< "$version"
          
          minor=$((minor + 1))
          patch='0'
          next_version="$major.$minor.$patch"
          
          timestamp=$(TZ="America/Chicago" date +"%Y%m%d")
          # Other Timezones
          # TZ="America/New_York" date +"%Y%m%d%H%M%S"
          # TZ="America/Chicago" date +"%Y%m%d%H%M%S"
          # TZ="America/Denver" date +"%Y%m%d%H%M%S"
          # TZ="America/Los_Angeles" date +"%Y%m%d%H%M%S"
          
          burrito_next_tag_without_build_suffix="burrito-next-${next_version}-${timestamp}${build_suffix}"
          burrito_next_versions=$(echo "$tags" | grep "$burrito_next_tag_without_build_suffix" | cat)
          
          build_count=$(echo -n "$burrito_next_versions" | wc -l)
          build_suffix=$(printf %02d $build_count)
          combined_patch_number=$((patch * 10000000000000000 + timestamp * 100 + build_count))
          
          
          
          echo "Burrito Version Tag: burrito-${next_version}"
          echo "Burrito Release Name: Burrito ${next_version}"
          echo "Burrito Embedded Versions: ${major} ${minor} ${patch}"
          echo "Burrito Next Version Tag: ${burrito_next_tag_without_build_suffix}${build_suffix}"
          echo "Burrito Next Version Tag: Burrito-next ${next_version} (${timestamp}${build_suffix})"
          echo "Burrito Next Embedded Versions: ${major} ${minor} ${combined_patch_number}"


  call-build:
    needs: get-version
    uses: ./.github/workflows/main.yml

  publish:
    needs: call-build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Download Burrito Package
        uses: actions/download-artifact@v4
        # This is failing for some reason
        #with:
        #  name: Burrito_Linux

      - name: Generate a random name
        id: version_number
        run: |
          UUID=$(uuidgen)
          echo "VERSION_NUMBER=${UUID}" >> "$GITHUB_ENV"
          echo "version_number=${UUID}" >> "$GITHUB_OUTPUT"

      - name: Zip up the download
        run: |
          mkdir -p "downloaded-artifact"
          zip -r downloaded-artifact/burrito-"$VERSION_NUMBER" Burrito_Linux

      # - name: Listfiles
      #   run: |
      #     tree .
      #     pwd

      # - name: Create a fake artifact
      #   run: |
      #     mkdir -p "downloaded-artifact"
      #     echo "Hello World" > downloaded-artifact/my_special_artifact.zip

      # - name: Tag the current commit with this tag
      #   run: |
      #     git tag -a "${$VERSION_NUMBER}" -m "Build ${$VERSION_NUMBER}" ${{ github.sha }}
      #     git push origin "${$VERSION_NUMBER}"

      - name: Upload a new release
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');

            const tag = "${{ steps.version_number.outputs.version_number }}";

            const githubToken = process.env.GITHUB_TOKEN;

            console.log(`Creating release with tag: ${tag}`);
            console.log(`using ${context.repo.owner} and ${context.repo.repo}`);
            console.log(`Found the release mode ${context.payload.inputs.release_type}`);

            const release = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: tag,
              name: "Burrito " + tag,
              body: "A new Automated release",
              target_commitish: '${{ github.sha }}',
              draft: true,
              prerelease: false,
            });

            const releaseId = release.data.id;

            console.log(`found release id ${releaseId}`);

            // 2. Upload assets
            const dir = 'downloaded-artifact';
            const files = fs.readdirSync(dir);
            for (const file of files) {
              const filePath = path.join(dir, file);
              const content = fs.readFileSync(filePath);
              const stats = fs.statSync(filePath);

              await github.rest.repos.uploadReleaseAsset({
                owner: context.repo.owner,
                repo: context.repo.repo,
                release_id: releaseId,
                name: file,
                data: content,
                headers: {
                  'content-type': 'application/octet-stream',
                  'content-length': stats.size,
                }
              });
            }
  
